default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 1441297
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test
